package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.BaseMajorModel;
import com.deao.dal.daomain.auto.BaseMajorModelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BaseMajorModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int countByExample(BaseMajorModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int deleteByExample(BaseMajorModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int insert(BaseMajorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int insertSelective(BaseMajorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    List<BaseMajorModel> selectByExample(BaseMajorModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    BaseMajorModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseMajorModel record, @Param("example") BaseMajorModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseMajorModel record, @Param("example") BaseMajorModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BaseMajorModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_major
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BaseMajorModel record);
}