package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.BaseAchievementRankingModel;
import com.deao.dal.daomain.auto.BaseAchievementRankingModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseAchievementRankingModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_achievement_ranking
     *
     * @mbggenerated
     */
    int countByExample(BaseAchievementRankingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_achievement_ranking
     *
     * @mbggenerated
     */
    int deleteByExample(BaseAchievementRankingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_achievement_ranking
     *
     * @mbggenerated
     */
    int insert(BaseAchievementRankingModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_achievement_ranking
     *
     * @mbggenerated
     */
    int insertSelective(BaseAchievementRankingModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_achievement_ranking
     *
     * @mbggenerated
     */
    List<BaseAchievementRankingModel> selectByExample(BaseAchievementRankingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_achievement_ranking
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BaseAchievementRankingModel record, @Param("example") BaseAchievementRankingModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_achievement_ranking
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BaseAchievementRankingModel record, @Param("example") BaseAchievementRankingModelExample example);
}