package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.OrderPaymentNotifyModel;
import com.deao.dal.daomain.auto.OrderPaymentNotifyModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderPaymentNotifyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_notify
     *
     * @mbggenerated
     */
    int countByExample(OrderPaymentNotifyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_notify
     *
     * @mbggenerated
     */
    int deleteByExample(OrderPaymentNotifyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_notify
     *
     * @mbggenerated
     */
    int insert(OrderPaymentNotifyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_notify
     *
     * @mbggenerated
     */
    int insertSelective(OrderPaymentNotifyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_notify
     *
     * @mbggenerated
     */
    List<OrderPaymentNotifyModel> selectByExample(OrderPaymentNotifyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_notify
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderPaymentNotifyModel record, @Param("example") OrderPaymentNotifyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_payment_notify
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderPaymentNotifyModel record, @Param("example") OrderPaymentNotifyModelExample example);
}