package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.OutsideMember;
import com.deao.dal.daomain.auto.OutsideMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutsideMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int countByExample(OutsideMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int deleteByExample(OutsideMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int insert(OutsideMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int insertSelective(OutsideMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    List<OutsideMember> selectByExample(OutsideMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    OutsideMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OutsideMember record, @Param("example") OutsideMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OutsideMember record, @Param("example") OutsideMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OutsideMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutsideMember record);
}