package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.OutsideMemberModel;
import com.deao.dal.daomain.auto.OutsideMemberModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutsideMemberModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int countByExample(OutsideMemberModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int deleteByExample(OutsideMemberModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int insert(OutsideMemberModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int insertSelective(OutsideMemberModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    List<OutsideMemberModel> selectByExample(OutsideMemberModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OutsideMemberModel record, @Param("example") OutsideMemberModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outside_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OutsideMemberModel record, @Param("example") OutsideMemberModelExample example);
}