package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.RecruitPlanModel;
import com.deao.dal.daomain.auto.RecruitPlanModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecruitPlanModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_plan
     *
     * @mbggenerated
     */
    int countByExample(RecruitPlanModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_plan
     *
     * @mbggenerated
     */
    int deleteByExample(RecruitPlanModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_plan
     *
     * @mbggenerated
     */
    int insert(RecruitPlanModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_plan
     *
     * @mbggenerated
     */
    int insertSelective(RecruitPlanModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_plan
     *
     * @mbggenerated
     */
    List<RecruitPlanModel> selectByExample(RecruitPlanModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_plan
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecruitPlanModel record, @Param("example") RecruitPlanModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_plan
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecruitPlanModel record, @Param("example") RecruitPlanModelExample example);
}