package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.SchoolMajorCardInfoModel;
import com.deao.dal.daomain.auto.SchoolMajorCardInfoModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchoolMajorCardInfoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major_card_info
     *
     * @mbggenerated
     */
    int countByExample(SchoolMajorCardInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major_card_info
     *
     * @mbggenerated
     */
    int deleteByExample(SchoolMajorCardInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major_card_info
     *
     * @mbggenerated
     */
    int insert(SchoolMajorCardInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major_card_info
     *
     * @mbggenerated
     */
    int insertSelective(SchoolMajorCardInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major_card_info
     *
     * @mbggenerated
     */
    List<SchoolMajorCardInfoModel> selectByExample(SchoolMajorCardInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major_card_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SchoolMajorCardInfoModel record, @Param("example") SchoolMajorCardInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_major_card_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SchoolMajorCardInfoModel record, @Param("example") SchoolMajorCardInfoModelExample example);
}