package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.SystemBasicConfigModel;
import com.deao.dal.daomain.auto.SystemBasicConfigModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemBasicConfigModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_basic_config
     *
     * @mbggenerated
     */
    int countByExample(SystemBasicConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_basic_config
     *
     * @mbggenerated
     */
    int deleteByExample(SystemBasicConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_basic_config
     *
     * @mbggenerated
     */
    int insert(SystemBasicConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_basic_config
     *
     * @mbggenerated
     */
    int insertSelective(SystemBasicConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_basic_config
     *
     * @mbggenerated
     */
    List<SystemBasicConfigModel> selectByExample(SystemBasicConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_basic_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemBasicConfigModel record, @Param("example") SystemBasicConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_basic_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemBasicConfigModel record, @Param("example") SystemBasicConfigModelExample example);
}