package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.SystemSearchRecordModel;
import com.deao.dal.daomain.auto.SystemSearchRecordModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemSearchRecordModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_search_record
     *
     * @mbggenerated
     */
    int countByExample(SystemSearchRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_search_record
     *
     * @mbggenerated
     */
    int deleteByExample(SystemSearchRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_search_record
     *
     * @mbggenerated
     */
    int insert(SystemSearchRecordModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_search_record
     *
     * @mbggenerated
     */
    int insertSelective(SystemSearchRecordModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_search_record
     *
     * @mbggenerated
     */
    List<SystemSearchRecordModel> selectByExample(SystemSearchRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_search_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemSearchRecordModel record, @Param("example") SystemSearchRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_search_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemSearchRecordModel record, @Param("example") SystemSearchRecordModelExample example);
}