package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.WechatMemberVolunteerRecordModel;
import com.deao.dal.daomain.auto.WechatMemberVolunteerRecordModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatMemberVolunteerRecordModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_volunteer_record
     *
     * @mbggenerated
     */
    int countByExample(WechatMemberVolunteerRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_volunteer_record
     *
     * @mbggenerated
     */
    int deleteByExample(WechatMemberVolunteerRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_volunteer_record
     *
     * @mbggenerated
     */
    int insert(WechatMemberVolunteerRecordModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_volunteer_record
     *
     * @mbggenerated
     */
    int insertSelective(WechatMemberVolunteerRecordModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_volunteer_record
     *
     * @mbggenerated
     */
    List<WechatMemberVolunteerRecordModel> selectByExample(WechatMemberVolunteerRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_volunteer_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatMemberVolunteerRecordModel record, @Param("example") WechatMemberVolunteerRecordModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_volunteer_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatMemberVolunteerRecordModel record, @Param("example") WechatMemberVolunteerRecordModelExample example);
}