package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.WechatChannelConfigModel;
import com.deao.dal.daomain.auto.WechatChannelConfigModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatChannelConfigModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_config
     *
     * @mbggenerated
     */
    int countByExample(WechatChannelConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_config
     *
     * @mbggenerated
     */
    int deleteByExample(WechatChannelConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_config
     *
     * @mbggenerated
     */
    int insert(WechatChannelConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_config
     *
     * @mbggenerated
     */
    int insertSelective(WechatChannelConfigModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_config
     *
     * @mbggenerated
     */
    List<WechatChannelConfigModel> selectByExample(WechatChannelConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatChannelConfigModel record, @Param("example") WechatChannelConfigModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatChannelConfigModel record, @Param("example") WechatChannelConfigModelExample example);
}