package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.WechatMemberAchievementModel;
import com.deao.dal.daomain.auto.WechatMemberAchievementModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatMemberAchievementModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_achievement
     *
     * @mbggenerated
     */
    int countByExample(WechatMemberAchievementModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_achievement
     *
     * @mbggenerated
     */
    int deleteByExample(WechatMemberAchievementModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_achievement
     *
     * @mbggenerated
     */
    int insert(WechatMemberAchievementModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_achievement
     *
     * @mbggenerated
     */
    int insertSelective(WechatMemberAchievementModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_achievement
     *
     * @mbggenerated
     */
    List<WechatMemberAchievementModel> selectByExample(WechatMemberAchievementModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_achievement
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatMemberAchievementModel record, @Param("example") WechatMemberAchievementModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_member_achievement
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatMemberAchievementModel record, @Param("example") WechatMemberAchievementModelExample example);
}