package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.WechatChannelDetailModel;
import com.deao.dal.daomain.auto.WechatChannelDetailModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatChannelDetailModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_detail
     *
     * @mbggenerated
     */
    int countByExample(WechatChannelDetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_detail
     *
     * @mbggenerated
     */
    int deleteByExample(WechatChannelDetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_detail
     *
     * @mbggenerated
     */
    int insert(WechatChannelDetailModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_detail
     *
     * @mbggenerated
     */
    int insertSelective(WechatChannelDetailModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_detail
     *
     * @mbggenerated
     */
    List<WechatChannelDetailModel> selectByExample(WechatChannelDetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WechatChannelDetailModel record, @Param("example") WechatChannelDetailModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_channel_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WechatChannelDetailModel record, @Param("example") WechatChannelDetailModelExample example);
}