package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.ZhaobanUserStudentModel;
import com.deao.dal.daomain.auto.ZhaobanUserStudentModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhaobanUserStudentModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_user_student
     *
     * @mbggenerated
     */
    int countByExample(ZhaobanUserStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_user_student
     *
     * @mbggenerated
     */
    int deleteByExample(ZhaobanUserStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_user_student
     *
     * @mbggenerated
     */
    int insert(ZhaobanUserStudentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_user_student
     *
     * @mbggenerated
     */
    int insertSelective(ZhaobanUserStudentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_user_student
     *
     * @mbggenerated
     */
    List<ZhaobanUserStudentModel> selectByExample(ZhaobanUserStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_user_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZhaobanUserStudentModel record, @Param("example") ZhaobanUserStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_user_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZhaobanUserStudentModel record, @Param("example") ZhaobanUserStudentModelExample example);
}