package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.ZhaobanStudentModel;
import com.deao.dal.daomain.auto.ZhaobanStudentModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhaobanStudentModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_student
     *
     * @mbggenerated
     */
    int countByExample(ZhaobanStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_student
     *
     * @mbggenerated
     */
    int deleteByExample(ZhaobanStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_student
     *
     * @mbggenerated
     */
    int insert(ZhaobanStudentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_student
     *
     * @mbggenerated
     */
    int insertSelective(ZhaobanStudentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_student
     *
     * @mbggenerated
     */
    List<ZhaobanStudentModel> selectByExample(ZhaobanStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_student
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZhaobanStudentModel record, @Param("example") ZhaobanStudentModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_student
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZhaobanStudentModel record, @Param("example") ZhaobanStudentModelExample example);
}