package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.ZhaobanTeacherInfoModel;
import com.deao.dal.daomain.auto.ZhaobanTeacherInfoModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhaobanTeacherInfoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_teacher_info
     *
     * @mbggenerated
     */
    int countByExample(ZhaobanTeacherInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_teacher_info
     *
     * @mbggenerated
     */
    int deleteByExample(ZhaobanTeacherInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_teacher_info
     *
     * @mbggenerated
     */
    int insert(ZhaobanTeacherInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_teacher_info
     *
     * @mbggenerated
     */
    int insertSelective(ZhaobanTeacherInfoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_teacher_info
     *
     * @mbggenerated
     */
    List<ZhaobanTeacherInfoModel> selectByExample(ZhaobanTeacherInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_teacher_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZhaobanTeacherInfoModel record, @Param("example") ZhaobanTeacherInfoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_teacher_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZhaobanTeacherInfoModel record, @Param("example") ZhaobanTeacherInfoModelExample example);
}