package com.deao.dal.dao.auto;

import com.deao.dal.daomain.auto.ZhaobanSecondCollegeModel;
import com.deao.dal.daomain.auto.ZhaobanSecondCollegeModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhaobanSecondCollegeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_second_college
     *
     * @mbggenerated
     */
    int countByExample(ZhaobanSecondCollegeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_second_college
     *
     * @mbggenerated
     */
    int deleteByExample(ZhaobanSecondCollegeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_second_college
     *
     * @mbggenerated
     */
    int insert(ZhaobanSecondCollegeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_second_college
     *
     * @mbggenerated
     */
    int insertSelective(ZhaobanSecondCollegeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_second_college
     *
     * @mbggenerated
     */
    List<ZhaobanSecondCollegeModel> selectByExample(ZhaobanSecondCollegeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_second_college
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZhaobanSecondCollegeModel record, @Param("example") ZhaobanSecondCollegeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhaoban_second_college
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZhaobanSecondCollegeModel record, @Param("example") ZhaobanSecondCollegeModelExample example);
}