package mybatisGenerator.com.model;

import java.util.Date;

public class SystemMobileCodeModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 手机号码
     *
     * @mbggenerated
     */
    private String phoneNumber;

    /**
     * 短信类型
     *
     * @mbggenerated
     */
    private String codeType;

    /**
     * 短信类型的值[登录/其他]
     *
     * @mbggenerated
     */
    private String codeTypeValues;

    /**
     * 验证码code
     *
     * @mbggenerated
     */
    private String yzmCode;

    /**
     * 开始时间
     *
     * @mbggenerated
     */
    private Date startTime;

    /**
     * 结束时间
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * 是否验证
     *
     * @mbggenerated
     */
    private String isValidate;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.id
     *
     * @return the value of system_mobile_code.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.id
     *
     * @param id the value for system_mobile_code.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.phone_number
     *
     * @return the value of system_mobile_code.phone_number
     *
     * @mbggenerated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.phone_number
     *
     * @param phoneNumber the value for system_mobile_code.phone_number
     *
     * @mbggenerated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.code_type
     *
     * @return the value of system_mobile_code.code_type
     *
     * @mbggenerated
     */
    public String getCodeType() {
        return codeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.code_type
     *
     * @param codeType the value for system_mobile_code.code_type
     *
     * @mbggenerated
     */
    public void setCodeType(String codeType) {
        this.codeType = codeType == null ? null : codeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.code_type_values
     *
     * @return the value of system_mobile_code.code_type_values
     *
     * @mbggenerated
     */
    public String getCodeTypeValues() {
        return codeTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.code_type_values
     *
     * @param codeTypeValues the value for system_mobile_code.code_type_values
     *
     * @mbggenerated
     */
    public void setCodeTypeValues(String codeTypeValues) {
        this.codeTypeValues = codeTypeValues == null ? null : codeTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.yzm_code
     *
     * @return the value of system_mobile_code.yzm_code
     *
     * @mbggenerated
     */
    public String getYzmCode() {
        return yzmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.yzm_code
     *
     * @param yzmCode the value for system_mobile_code.yzm_code
     *
     * @mbggenerated
     */
    public void setYzmCode(String yzmCode) {
        this.yzmCode = yzmCode == null ? null : yzmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.start_time
     *
     * @return the value of system_mobile_code.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.start_time
     *
     * @param startTime the value for system_mobile_code.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.end_time
     *
     * @return the value of system_mobile_code.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.end_time
     *
     * @param endTime the value for system_mobile_code.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.is_validate
     *
     * @return the value of system_mobile_code.is_validate
     *
     * @mbggenerated
     */
    public String getIsValidate() {
        return isValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.is_validate
     *
     * @param isValidate the value for system_mobile_code.is_validate
     *
     * @mbggenerated
     */
    public void setIsValidate(String isValidate) {
        this.isValidate = isValidate == null ? null : isValidate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.remark
     *
     * @return the value of system_mobile_code.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.remark
     *
     * @param remark the value for system_mobile_code.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.create_time
     *
     * @return the value of system_mobile_code.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.create_time
     *
     * @param createTime the value for system_mobile_code.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.update_time
     *
     * @return the value of system_mobile_code.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.update_time
     *
     * @param updateTime the value for system_mobile_code.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_mobile_code.is_delete
     *
     * @return the value of system_mobile_code.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_mobile_code.is_delete
     *
     * @param isDelete the value for system_mobile_code.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}