package mybatisGenerator.com.model;

import java.util.Date;

public class SystemOptLogModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 外联外部no
     *
     * @mbggenerated
     */
    private String relationNo;

    /**
     * 操作类型
     *
     * @mbggenerated
     */
    private String optType;

    /**
     * 操作类型的值
     *
     * @mbggenerated
     */
    private String optTypeValues;

    /**
     * 操作时间
     *
     * @mbggenerated
     */
    private Date optTime;

    /**
     * 操作者userid
     *
     * @mbggenerated
     */
    private String optUserId;

    /**
     * 操作者username
     *
     * @mbggenerated
     */
    private String optUserName;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.id
     *
     * @return the value of system_opt_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.id
     *
     * @param id the value for system_opt_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.relation_no
     *
     * @return the value of system_opt_log.relation_no
     *
     * @mbggenerated
     */
    public String getRelationNo() {
        return relationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.relation_no
     *
     * @param relationNo the value for system_opt_log.relation_no
     *
     * @mbggenerated
     */
    public void setRelationNo(String relationNo) {
        this.relationNo = relationNo == null ? null : relationNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.opt_type
     *
     * @return the value of system_opt_log.opt_type
     *
     * @mbggenerated
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.opt_type
     *
     * @param optType the value for system_opt_log.opt_type
     *
     * @mbggenerated
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.opt_type_values
     *
     * @return the value of system_opt_log.opt_type_values
     *
     * @mbggenerated
     */
    public String getOptTypeValues() {
        return optTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.opt_type_values
     *
     * @param optTypeValues the value for system_opt_log.opt_type_values
     *
     * @mbggenerated
     */
    public void setOptTypeValues(String optTypeValues) {
        this.optTypeValues = optTypeValues == null ? null : optTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.opt_time
     *
     * @return the value of system_opt_log.opt_time
     *
     * @mbggenerated
     */
    public Date getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.opt_time
     *
     * @param optTime the value for system_opt_log.opt_time
     *
     * @mbggenerated
     */
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.opt_user_id
     *
     * @return the value of system_opt_log.opt_user_id
     *
     * @mbggenerated
     */
    public String getOptUserId() {
        return optUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.opt_user_id
     *
     * @param optUserId the value for system_opt_log.opt_user_id
     *
     * @mbggenerated
     */
    public void setOptUserId(String optUserId) {
        this.optUserId = optUserId == null ? null : optUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.opt_user_name
     *
     * @return the value of system_opt_log.opt_user_name
     *
     * @mbggenerated
     */
    public String getOptUserName() {
        return optUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.opt_user_name
     *
     * @param optUserName the value for system_opt_log.opt_user_name
     *
     * @mbggenerated
     */
    public void setOptUserName(String optUserName) {
        this.optUserName = optUserName == null ? null : optUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.remark
     *
     * @return the value of system_opt_log.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.remark
     *
     * @param remark the value for system_opt_log.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.remark_extend
     *
     * @return the value of system_opt_log.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.remark_extend
     *
     * @param remarkExtend the value for system_opt_log.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.create_time
     *
     * @return the value of system_opt_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.create_time
     *
     * @param createTime the value for system_opt_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.update_time
     *
     * @return the value of system_opt_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.update_time
     *
     * @param updateTime the value for system_opt_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_opt_log.is_delete
     *
     * @return the value of system_opt_log.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_opt_log.is_delete
     *
     * @param isDelete the value for system_opt_log.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}