package mybatisGenerator.com.dao;

import mybatisGenerator.com.model.SystemMobileCodeModel;
import mybatisGenerator.com.model.SystemMobileCodeModelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SystemMobileCodeModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int countByExample(SystemMobileCodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int deleteByExample(SystemMobileCodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int insert(SystemMobileCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int insertSelective(SystemMobileCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    List<SystemMobileCodeModel> selectByExample(SystemMobileCodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    SystemMobileCodeModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemMobileCodeModel record, @Param("example") SystemMobileCodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemMobileCodeModel record, @Param("example") SystemMobileCodeModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemMobileCodeModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_mobile_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemMobileCodeModel record);
}