package mybatisGenerator.com.dao;

import java.util.List;
import mybatisGenerator.com.model.SystemOptLogModel;
import mybatisGenerator.com.model.SystemOptLogModelExample;
import org.apache.ibatis.annotations.Param;

public interface SystemOptLogModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int countByExample(SystemOptLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int deleteByExample(SystemOptLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int insert(SystemOptLogModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int insertSelective(SystemOptLogModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    List<SystemOptLogModel> selectByExample(SystemOptLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    SystemOptLogModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SystemOptLogModel record, @Param("example") SystemOptLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SystemOptLogModel record, @Param("example") SystemOptLogModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SystemOptLogModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_opt_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SystemOptLogModel record);
}