package com.deao.dal.daomain.auto;

import java.util.Date;

public class BaseMajorModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 专业名字
     *
     * @mbggenerated
     */
    private String majorName;

    /**
     * 一级所属分类
     *
     * @mbggenerated
     */
    private Integer oneLevel;

    /**
     * 二级所属分类
     *
     * @mbggenerated
     */
    private Integer twoLevel;

    /**
     * 三级所属分类
     *
     * @mbggenerated
     */
    private Integer threeLevel;

    /**
     * 年份
     *
     * @mbggenerated
     */
    private String year;

    /**
     * 排序[数字越小越靠前]
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * 专业拼音首字母
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.id
     *
     * @return the value of base_major.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.id
     *
     * @param id the value for base_major.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.major_name
     *
     * @return the value of base_major.major_name
     *
     * @mbggenerated
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.major_name
     *
     * @param majorName the value for base_major.major_name
     *
     * @mbggenerated
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.one_level
     *
     * @return the value of base_major.one_level
     *
     * @mbggenerated
     */
    public Integer getOneLevel() {
        return oneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.one_level
     *
     * @param oneLevel the value for base_major.one_level
     *
     * @mbggenerated
     */
    public void setOneLevel(Integer oneLevel) {
        this.oneLevel = oneLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.two_level
     *
     * @return the value of base_major.two_level
     *
     * @mbggenerated
     */
    public Integer getTwoLevel() {
        return twoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.two_level
     *
     * @param twoLevel the value for base_major.two_level
     *
     * @mbggenerated
     */
    public void setTwoLevel(Integer twoLevel) {
        this.twoLevel = twoLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.three_level
     *
     * @return the value of base_major.three_level
     *
     * @mbggenerated
     */
    public Integer getThreeLevel() {
        return threeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.three_level
     *
     * @param threeLevel the value for base_major.three_level
     *
     * @mbggenerated
     */
    public void setThreeLevel(Integer threeLevel) {
        this.threeLevel = threeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.year
     *
     * @return the value of base_major.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.year
     *
     * @param year the value for base_major.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.sort
     *
     * @return the value of base_major.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.sort
     *
     * @param sort the value for base_major.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.pinyin
     *
     * @return the value of base_major.pinyin
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.pinyin
     *
     * @param pinyin the value for base_major.pinyin
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.remark
     *
     * @return the value of base_major.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.remark
     *
     * @param remark the value for base_major.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.remark_extend
     *
     * @return the value of base_major.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.remark_extend
     *
     * @param remarkExtend the value for base_major.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.create_time
     *
     * @return the value of base_major.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.create_time
     *
     * @param createTime the value for base_major.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.update_time
     *
     * @return the value of base_major.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.update_time
     *
     * @param updateTime the value for base_major.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_major.is_delete
     *
     * @return the value of base_major.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_major.is_delete
     *
     * @param isDelete the value for base_major.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}