package com.deao.dal.daomain.auto;

import java.math.BigDecimal;
import java.util.Date;

public class BaseAchievementRankingModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 年份
     *
     * @mbggenerated
     */
    private String year;

    /**
     * 教育类型
     *
     * @mbggenerated
     */
    private String eduType;

    /**
     * 教育类型的值
     *
     * @mbggenerated
     */
    private String eduTypeValues;

    /**
     * 类别名字
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * 分数
     *
     * @mbggenerated
     */
    private BigDecimal fraction;

    /**
     * 人数
     *
     * @mbggenerated
     */
    private String peopleCount;

    /**
     * 排名
     *
     * @mbggenerated
     */
    private String ranking;

    /**
     * 备注[ 存放本科专科字段 见枚举 EnumsEducationalLevel ]
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.id
     *
     * @return the value of base_achievement_ranking.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.id
     *
     * @param id the value for base_achievement_ranking.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.year
     *
     * @return the value of base_achievement_ranking.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.year
     *
     * @param year the value for base_achievement_ranking.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.edu_type
     *
     * @return the value of base_achievement_ranking.edu_type
     *
     * @mbggenerated
     */
    public String getEduType() {
        return eduType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.edu_type
     *
     * @param eduType the value for base_achievement_ranking.edu_type
     *
     * @mbggenerated
     */
    public void setEduType(String eduType) {
        this.eduType = eduType == null ? null : eduType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.edu_type_values
     *
     * @return the value of base_achievement_ranking.edu_type_values
     *
     * @mbggenerated
     */
    public String getEduTypeValues() {
        return eduTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.edu_type_values
     *
     * @param eduTypeValues the value for base_achievement_ranking.edu_type_values
     *
     * @mbggenerated
     */
    public void setEduTypeValues(String eduTypeValues) {
        this.eduTypeValues = eduTypeValues == null ? null : eduTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.category_name
     *
     * @return the value of base_achievement_ranking.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.category_name
     *
     * @param categoryName the value for base_achievement_ranking.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.fraction
     *
     * @return the value of base_achievement_ranking.fraction
     *
     * @mbggenerated
     */
    public BigDecimal getFraction() {
        return fraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.fraction
     *
     * @param fraction the value for base_achievement_ranking.fraction
     *
     * @mbggenerated
     */
    public void setFraction(BigDecimal fraction) {
        this.fraction = fraction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.people_count
     *
     * @return the value of base_achievement_ranking.people_count
     *
     * @mbggenerated
     */
    public String getPeopleCount() {
        return peopleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.people_count
     *
     * @param peopleCount the value for base_achievement_ranking.people_count
     *
     * @mbggenerated
     */
    public void setPeopleCount(String peopleCount) {
        this.peopleCount = peopleCount == null ? null : peopleCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.ranking
     *
     * @return the value of base_achievement_ranking.ranking
     *
     * @mbggenerated
     */
    public String getRanking() {
        return ranking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.ranking
     *
     * @param ranking the value for base_achievement_ranking.ranking
     *
     * @mbggenerated
     */
    public void setRanking(String ranking) {
        this.ranking = ranking == null ? null : ranking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.remark
     *
     * @return the value of base_achievement_ranking.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.remark
     *
     * @param remark the value for base_achievement_ranking.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.remark_extend
     *
     * @return the value of base_achievement_ranking.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.remark_extend
     *
     * @param remarkExtend the value for base_achievement_ranking.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.create_time
     *
     * @return the value of base_achievement_ranking.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.create_time
     *
     * @param createTime the value for base_achievement_ranking.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.update_time
     *
     * @return the value of base_achievement_ranking.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.update_time
     *
     * @param updateTime the value for base_achievement_ranking.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_achievement_ranking.is_delete
     *
     * @return the value of base_achievement_ranking.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_achievement_ranking.is_delete
     *
     * @param isDelete the value for base_achievement_ranking.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}