package com.deao.dal.daomain.auto;

import java.util.Date;

public class BaseHotSearchModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 关系类型
     *
     * @mbggenerated
     */
    private String relationType;

    /**
     * 关系类型的值
     *
     * @mbggenerated
     */
    private String relationTypeValues;

    /**
     * 关系id
     *
     * @mbggenerated
     */
    private Integer relationId;

    /**
     * 排序[数字越小越靠前]
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.id
     *
     * @return the value of base_hot_search.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.id
     *
     * @param id the value for base_hot_search.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.relation_type
     *
     * @return the value of base_hot_search.relation_type
     *
     * @mbggenerated
     */
    public String getRelationType() {
        return relationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.relation_type
     *
     * @param relationType the value for base_hot_search.relation_type
     *
     * @mbggenerated
     */
    public void setRelationType(String relationType) {
        this.relationType = relationType == null ? null : relationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.relation_type_values
     *
     * @return the value of base_hot_search.relation_type_values
     *
     * @mbggenerated
     */
    public String getRelationTypeValues() {
        return relationTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.relation_type_values
     *
     * @param relationTypeValues the value for base_hot_search.relation_type_values
     *
     * @mbggenerated
     */
    public void setRelationTypeValues(String relationTypeValues) {
        this.relationTypeValues = relationTypeValues == null ? null : relationTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.relation_id
     *
     * @return the value of base_hot_search.relation_id
     *
     * @mbggenerated
     */
    public Integer getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.relation_id
     *
     * @param relationId the value for base_hot_search.relation_id
     *
     * @mbggenerated
     */
    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.sort
     *
     * @return the value of base_hot_search.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.sort
     *
     * @param sort the value for base_hot_search.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.remark
     *
     * @return the value of base_hot_search.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.remark
     *
     * @param remark the value for base_hot_search.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.remark_extend
     *
     * @return the value of base_hot_search.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.remark_extend
     *
     * @param remarkExtend the value for base_hot_search.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.create_time
     *
     * @return the value of base_hot_search.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.create_time
     *
     * @param createTime the value for base_hot_search.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.update_time
     *
     * @return the value of base_hot_search.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.update_time
     *
     * @param updateTime the value for base_hot_search.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_hot_search.is_delete
     *
     * @return the value of base_hot_search.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_hot_search.is_delete
     *
     * @param isDelete the value for base_hot_search.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}