package com.deao.dal.daomain.auto;

import java.util.Date;

public class BaseSchoolModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 学校code
     *
     * @mbggenerated
     */
    private String schoolCode;

    /**
     * 学校名字
     *
     * @mbggenerated
     */
    private String schoolName;

    /**
     * 学校性质
     *
     * @mbggenerated
     */
    private String schoolNature;

    /**
     * 学校性质的值
     *
     * @mbggenerated
     */
    private String schoolNatureValues;

    /**
     * 学校地址
     *
     * @mbggenerated
     */
    private String schoolAddress;

    /**
     * 学校独立网址
     *
     * @mbggenerated
     */
    private String schoolUrl;

    /**
     * 是否展示学校性质
     *
     * @mbggenerated
     */
    private String isNature;

    /**
     * 是否展示学校独立网址
     *
     * @mbggenerated
     */
    private String isUrl;

    /**
     * 是否入驻
     *
     * @mbggenerated
     */
    private String isSettledin;

    /**
     * 年份
     *
     * @mbggenerated
     */
    private String year;

    /**
     * 排序[数字越小越靠前]
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.id
     *
     * @return the value of base_school.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.id
     *
     * @param id the value for base_school.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.school_code
     *
     * @return the value of base_school.school_code
     *
     * @mbggenerated
     */
    public String getSchoolCode() {
        return schoolCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.school_code
     *
     * @param schoolCode the value for base_school.school_code
     *
     * @mbggenerated
     */
    public void setSchoolCode(String schoolCode) {
        this.schoolCode = schoolCode == null ? null : schoolCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.school_name
     *
     * @return the value of base_school.school_name
     *
     * @mbggenerated
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.school_name
     *
     * @param schoolName the value for base_school.school_name
     *
     * @mbggenerated
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.school_nature
     *
     * @return the value of base_school.school_nature
     *
     * @mbggenerated
     */
    public String getSchoolNature() {
        return schoolNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.school_nature
     *
     * @param schoolNature the value for base_school.school_nature
     *
     * @mbggenerated
     */
    public void setSchoolNature(String schoolNature) {
        this.schoolNature = schoolNature == null ? null : schoolNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.school_nature_values
     *
     * @return the value of base_school.school_nature_values
     *
     * @mbggenerated
     */
    public String getSchoolNatureValues() {
        return schoolNatureValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.school_nature_values
     *
     * @param schoolNatureValues the value for base_school.school_nature_values
     *
     * @mbggenerated
     */
    public void setSchoolNatureValues(String schoolNatureValues) {
        this.schoolNatureValues = schoolNatureValues == null ? null : schoolNatureValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.school_address
     *
     * @return the value of base_school.school_address
     *
     * @mbggenerated
     */
    public String getSchoolAddress() {
        return schoolAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.school_address
     *
     * @param schoolAddress the value for base_school.school_address
     *
     * @mbggenerated
     */
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress == null ? null : schoolAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.school_url
     *
     * @return the value of base_school.school_url
     *
     * @mbggenerated
     */
    public String getSchoolUrl() {
        return schoolUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.school_url
     *
     * @param schoolUrl the value for base_school.school_url
     *
     * @mbggenerated
     */
    public void setSchoolUrl(String schoolUrl) {
        this.schoolUrl = schoolUrl == null ? null : schoolUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.is_nature
     *
     * @return the value of base_school.is_nature
     *
     * @mbggenerated
     */
    public String getIsNature() {
        return isNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.is_nature
     *
     * @param isNature the value for base_school.is_nature
     *
     * @mbggenerated
     */
    public void setIsNature(String isNature) {
        this.isNature = isNature == null ? null : isNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.is_url
     *
     * @return the value of base_school.is_url
     *
     * @mbggenerated
     */
    public String getIsUrl() {
        return isUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.is_url
     *
     * @param isUrl the value for base_school.is_url
     *
     * @mbggenerated
     */
    public void setIsUrl(String isUrl) {
        this.isUrl = isUrl == null ? null : isUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.is_settledin
     *
     * @return the value of base_school.is_settledin
     *
     * @mbggenerated
     */
    public String getIsSettledin() {
        return isSettledin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.is_settledin
     *
     * @param isSettledin the value for base_school.is_settledin
     *
     * @mbggenerated
     */
    public void setIsSettledin(String isSettledin) {
        this.isSettledin = isSettledin == null ? null : isSettledin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.year
     *
     * @return the value of base_school.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.year
     *
     * @param year the value for base_school.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.sort
     *
     * @return the value of base_school.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.sort
     *
     * @param sort the value for base_school.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.remark
     *
     * @return the value of base_school.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.remark
     *
     * @param remark the value for base_school.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.remark_extend
     *
     * @return the value of base_school.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.remark_extend
     *
     * @param remarkExtend the value for base_school.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.create_time
     *
     * @return the value of base_school.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.create_time
     *
     * @param createTime the value for base_school.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.update_time
     *
     * @return the value of base_school.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.update_time
     *
     * @param updateTime the value for base_school.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_school.is_delete
     *
     * @return the value of base_school.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_school.is_delete
     *
     * @param isDelete the value for base_school.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}