package com.deao.dal.daomain.auto;

import java.util.Date;

public class BaseHighSchoolModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 高中学校名字
     *
     * @mbggenerated
     */
    private String highSchoolName;

    /**
     * 区Id
     *
     * @mbggenerated
     */
    private String areaId;

    /**
     * 区 名字
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * 教育类型
     *
     * @mbggenerated
     */
    private String eduType;

    /**
     * 教育类型的值
     *
     * @mbggenerated
     */
    private String eduTypeValues;

    /**
     * 排序[数字越小越靠前]
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.id
     *
     * @return the value of base_high_school.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.id
     *
     * @param id the value for base_high_school.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.high_school_name
     *
     * @return the value of base_high_school.high_school_name
     *
     * @mbggenerated
     */
    public String getHighSchoolName() {
        return highSchoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.high_school_name
     *
     * @param highSchoolName the value for base_high_school.high_school_name
     *
     * @mbggenerated
     */
    public void setHighSchoolName(String highSchoolName) {
        this.highSchoolName = highSchoolName == null ? null : highSchoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.area_id
     *
     * @return the value of base_high_school.area_id
     *
     * @mbggenerated
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.area_id
     *
     * @param areaId the value for base_high_school.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.area_name
     *
     * @return the value of base_high_school.area_name
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.area_name
     *
     * @param areaName the value for base_high_school.area_name
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.edu_type
     *
     * @return the value of base_high_school.edu_type
     *
     * @mbggenerated
     */
    public String getEduType() {
        return eduType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.edu_type
     *
     * @param eduType the value for base_high_school.edu_type
     *
     * @mbggenerated
     */
    public void setEduType(String eduType) {
        this.eduType = eduType == null ? null : eduType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.edu_type_values
     *
     * @return the value of base_high_school.edu_type_values
     *
     * @mbggenerated
     */
    public String getEduTypeValues() {
        return eduTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.edu_type_values
     *
     * @param eduTypeValues the value for base_high_school.edu_type_values
     *
     * @mbggenerated
     */
    public void setEduTypeValues(String eduTypeValues) {
        this.eduTypeValues = eduTypeValues == null ? null : eduTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.sort
     *
     * @return the value of base_high_school.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.sort
     *
     * @param sort the value for base_high_school.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.remark
     *
     * @return the value of base_high_school.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.remark
     *
     * @param remark the value for base_high_school.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.remark_extend
     *
     * @return the value of base_high_school.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.remark_extend
     *
     * @param remarkExtend the value for base_high_school.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.create_time
     *
     * @return the value of base_high_school.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.create_time
     *
     * @param createTime the value for base_high_school.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.update_time
     *
     * @return the value of base_high_school.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.update_time
     *
     * @param updateTime the value for base_high_school.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_high_school.is_delete
     *
     * @return the value of base_high_school.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_high_school.is_delete
     *
     * @param isDelete the value for base_high_school.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}