package com.deao.dal.daomain.auto;

import java.util.Date;

public class OrderPaymentNotifyModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 商户订单号
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * 支付类型
     *
     * @mbggenerated
     */
    private String paymentType;

    /**
     * 支付类型值[微信支付宝解锁]
     *
     * @mbggenerated
     */
    private String paymentTypeValues;

    /**
     * 微信支付订单号
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * 支付完成时间
     *
     * @mbggenerated
     */
    private String notifyTime;

    /**
     * 付款银行
     *
     * @mbggenerated
     */
    private String bankType;

    /**
     * 现金支付金额
     *
     * @mbggenerated
     */
    private String cashFee;

    /**
     * 交易类型JSAPI、NATIVE、APP
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.id
     *
     * @return the value of order_payment_notify.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.id
     *
     * @param id the value for order_payment_notify.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.out_trade_no
     *
     * @return the value of order_payment_notify.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.out_trade_no
     *
     * @param outTradeNo the value for order_payment_notify.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.payment_type
     *
     * @return the value of order_payment_notify.payment_type
     *
     * @mbggenerated
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.payment_type
     *
     * @param paymentType the value for order_payment_notify.payment_type
     *
     * @mbggenerated
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType == null ? null : paymentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.payment_type_values
     *
     * @return the value of order_payment_notify.payment_type_values
     *
     * @mbggenerated
     */
    public String getPaymentTypeValues() {
        return paymentTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.payment_type_values
     *
     * @param paymentTypeValues the value for order_payment_notify.payment_type_values
     *
     * @mbggenerated
     */
    public void setPaymentTypeValues(String paymentTypeValues) {
        this.paymentTypeValues = paymentTypeValues == null ? null : paymentTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.transaction_id
     *
     * @return the value of order_payment_notify.transaction_id
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.transaction_id
     *
     * @param transactionId the value for order_payment_notify.transaction_id
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.notify_time
     *
     * @return the value of order_payment_notify.notify_time
     *
     * @mbggenerated
     */
    public String getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.notify_time
     *
     * @param notifyTime the value for order_payment_notify.notify_time
     *
     * @mbggenerated
     */
    public void setNotifyTime(String notifyTime) {
        this.notifyTime = notifyTime == null ? null : notifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.bank_type
     *
     * @return the value of order_payment_notify.bank_type
     *
     * @mbggenerated
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.bank_type
     *
     * @param bankType the value for order_payment_notify.bank_type
     *
     * @mbggenerated
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.cash_fee
     *
     * @return the value of order_payment_notify.cash_fee
     *
     * @mbggenerated
     */
    public String getCashFee() {
        return cashFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.cash_fee
     *
     * @param cashFee the value for order_payment_notify.cash_fee
     *
     * @mbggenerated
     */
    public void setCashFee(String cashFee) {
        this.cashFee = cashFee == null ? null : cashFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.trade_type
     *
     * @return the value of order_payment_notify.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.trade_type
     *
     * @param tradeType the value for order_payment_notify.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.remark
     *
     * @return the value of order_payment_notify.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.remark
     *
     * @param remark the value for order_payment_notify.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.remark_extend
     *
     * @return the value of order_payment_notify.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.remark_extend
     *
     * @param remarkExtend the value for order_payment_notify.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.create_time
     *
     * @return the value of order_payment_notify.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.create_time
     *
     * @param createTime the value for order_payment_notify.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.update_time
     *
     * @return the value of order_payment_notify.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.update_time
     *
     * @param updateTime the value for order_payment_notify.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payment_notify.is_delete
     *
     * @return the value of order_payment_notify.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payment_notify.is_delete
     *
     * @param isDelete the value for order_payment_notify.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}