package com.deao.dal.daomain.auto;

import java.math.BigDecimal;
import java.util.Date;

public class ProxyConfigInfoModel {
    /**
     * id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 代理名称
     *
     * @mbggenerated
     */
    private String proxyName;

    /**
     * 代理二维码
     *
     * @mbggenerated
     */
    private String proxyUrl;

    /**
     * 推广人数
     *
     * @mbggenerated
     */
    private Integer extensionAccount;

    /**
     * 注册人数
     *
     * @mbggenerated
     */
    private Integer registerAccount;

    /**
     * 志愿订单数
     *
     * @mbggenerated
     */
    private Integer volunteerAccount;

    /**
     * 咨询订单数
     *
     * @mbggenerated
     */
    private Integer consultAccount;

    /**
     * 推广总收益
     *
     * @mbggenerated
     */
    private BigDecimal extensionAmount;

    /**
     * 志愿收益
     *
     * @mbggenerated
     */
    private BigDecimal volunteerAmount;

    /**
     * 咨询收益
     *
     * @mbggenerated
     */
    private BigDecimal consultAmount;

    /**
     * 唯一标识字符串
     *
     * @mbggenerated
     */
    private String unionStr;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.id
     *
     * @return the value of proxy_config_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.id
     *
     * @param id the value for proxy_config_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.proxy_name
     *
     * @return the value of proxy_config_info.proxy_name
     *
     * @mbggenerated
     */
    public String getProxyName() {
        return proxyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.proxy_name
     *
     * @param proxyName the value for proxy_config_info.proxy_name
     *
     * @mbggenerated
     */
    public void setProxyName(String proxyName) {
        this.proxyName = proxyName == null ? null : proxyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.proxy_url
     *
     * @return the value of proxy_config_info.proxy_url
     *
     * @mbggenerated
     */
    public String getProxyUrl() {
        return proxyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.proxy_url
     *
     * @param proxyUrl the value for proxy_config_info.proxy_url
     *
     * @mbggenerated
     */
    public void setProxyUrl(String proxyUrl) {
        this.proxyUrl = proxyUrl == null ? null : proxyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.extension_account
     *
     * @return the value of proxy_config_info.extension_account
     *
     * @mbggenerated
     */
    public Integer getExtensionAccount() {
        return extensionAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.extension_account
     *
     * @param extensionAccount the value for proxy_config_info.extension_account
     *
     * @mbggenerated
     */
    public void setExtensionAccount(Integer extensionAccount) {
        this.extensionAccount = extensionAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.register_account
     *
     * @return the value of proxy_config_info.register_account
     *
     * @mbggenerated
     */
    public Integer getRegisterAccount() {
        return registerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.register_account
     *
     * @param registerAccount the value for proxy_config_info.register_account
     *
     * @mbggenerated
     */
    public void setRegisterAccount(Integer registerAccount) {
        this.registerAccount = registerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.volunteer_account
     *
     * @return the value of proxy_config_info.volunteer_account
     *
     * @mbggenerated
     */
    public Integer getVolunteerAccount() {
        return volunteerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.volunteer_account
     *
     * @param volunteerAccount the value for proxy_config_info.volunteer_account
     *
     * @mbggenerated
     */
    public void setVolunteerAccount(Integer volunteerAccount) {
        this.volunteerAccount = volunteerAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.consult_account
     *
     * @return the value of proxy_config_info.consult_account
     *
     * @mbggenerated
     */
    public Integer getConsultAccount() {
        return consultAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.consult_account
     *
     * @param consultAccount the value for proxy_config_info.consult_account
     *
     * @mbggenerated
     */
    public void setConsultAccount(Integer consultAccount) {
        this.consultAccount = consultAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.extension_amount
     *
     * @return the value of proxy_config_info.extension_amount
     *
     * @mbggenerated
     */
    public BigDecimal getExtensionAmount() {
        return extensionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.extension_amount
     *
     * @param extensionAmount the value for proxy_config_info.extension_amount
     *
     * @mbggenerated
     */
    public void setExtensionAmount(BigDecimal extensionAmount) {
        this.extensionAmount = extensionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.volunteer_amount
     *
     * @return the value of proxy_config_info.volunteer_amount
     *
     * @mbggenerated
     */
    public BigDecimal getVolunteerAmount() {
        return volunteerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.volunteer_amount
     *
     * @param volunteerAmount the value for proxy_config_info.volunteer_amount
     *
     * @mbggenerated
     */
    public void setVolunteerAmount(BigDecimal volunteerAmount) {
        this.volunteerAmount = volunteerAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.consult_amount
     *
     * @return the value of proxy_config_info.consult_amount
     *
     * @mbggenerated
     */
    public BigDecimal getConsultAmount() {
        return consultAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.consult_amount
     *
     * @param consultAmount the value for proxy_config_info.consult_amount
     *
     * @mbggenerated
     */
    public void setConsultAmount(BigDecimal consultAmount) {
        this.consultAmount = consultAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.union_str
     *
     * @return the value of proxy_config_info.union_str
     *
     * @mbggenerated
     */
    public String getUnionStr() {
        return unionStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.union_str
     *
     * @param unionStr the value for proxy_config_info.union_str
     *
     * @mbggenerated
     */
    public void setUnionStr(String unionStr) {
        this.unionStr = unionStr == null ? null : unionStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.remark
     *
     * @return the value of proxy_config_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.remark
     *
     * @param remark the value for proxy_config_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.remark_extend
     *
     * @return the value of proxy_config_info.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.remark_extend
     *
     * @param remarkExtend the value for proxy_config_info.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.create_time
     *
     * @return the value of proxy_config_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.create_time
     *
     * @param createTime the value for proxy_config_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.update_time
     *
     * @return the value of proxy_config_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.update_time
     *
     * @param updateTime the value for proxy_config_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_config_info.is_delete
     *
     * @return the value of proxy_config_info.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_config_info.is_delete
     *
     * @param isDelete the value for proxy_config_info.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}