package com.deao.dal.daomain.auto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProxyConfigInfoModelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public ProxyConfigInfoModelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProxyNameIsNull() {
            addCriterion("proxy_name is null");
            return (Criteria) this;
        }

        public Criteria andProxyNameIsNotNull() {
            addCriterion("proxy_name is not null");
            return (Criteria) this;
        }

        public Criteria andProxyNameEqualTo(String value) {
            addCriterion("proxy_name =", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameNotEqualTo(String value) {
            addCriterion("proxy_name <>", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameGreaterThan(String value) {
            addCriterion("proxy_name >", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameGreaterThanOrEqualTo(String value) {
            addCriterion("proxy_name >=", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameLessThan(String value) {
            addCriterion("proxy_name <", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameLessThanOrEqualTo(String value) {
            addCriterion("proxy_name <=", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameLike(String value) {
            addCriterion("proxy_name like", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameNotLike(String value) {
            addCriterion("proxy_name not like", value, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameIn(List<String> values) {
            addCriterion("proxy_name in", values, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameNotIn(List<String> values) {
            addCriterion("proxy_name not in", values, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameBetween(String value1, String value2) {
            addCriterion("proxy_name between", value1, value2, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyNameNotBetween(String value1, String value2) {
            addCriterion("proxy_name not between", value1, value2, "proxyName");
            return (Criteria) this;
        }

        public Criteria andProxyUrlIsNull() {
            addCriterion("proxy_url is null");
            return (Criteria) this;
        }

        public Criteria andProxyUrlIsNotNull() {
            addCriterion("proxy_url is not null");
            return (Criteria) this;
        }

        public Criteria andProxyUrlEqualTo(String value) {
            addCriterion("proxy_url =", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlNotEqualTo(String value) {
            addCriterion("proxy_url <>", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlGreaterThan(String value) {
            addCriterion("proxy_url >", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("proxy_url >=", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlLessThan(String value) {
            addCriterion("proxy_url <", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlLessThanOrEqualTo(String value) {
            addCriterion("proxy_url <=", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlLike(String value) {
            addCriterion("proxy_url like", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlNotLike(String value) {
            addCriterion("proxy_url not like", value, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlIn(List<String> values) {
            addCriterion("proxy_url in", values, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlNotIn(List<String> values) {
            addCriterion("proxy_url not in", values, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlBetween(String value1, String value2) {
            addCriterion("proxy_url between", value1, value2, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andProxyUrlNotBetween(String value1, String value2) {
            addCriterion("proxy_url not between", value1, value2, "proxyUrl");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountIsNull() {
            addCriterion("extension_account is null");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountIsNotNull() {
            addCriterion("extension_account is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountEqualTo(Integer value) {
            addCriterion("extension_account =", value, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountNotEqualTo(Integer value) {
            addCriterion("extension_account <>", value, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountGreaterThan(Integer value) {
            addCriterion("extension_account >", value, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("extension_account >=", value, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountLessThan(Integer value) {
            addCriterion("extension_account <", value, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountLessThanOrEqualTo(Integer value) {
            addCriterion("extension_account <=", value, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountIn(List<Integer> values) {
            addCriterion("extension_account in", values, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountNotIn(List<Integer> values) {
            addCriterion("extension_account not in", values, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountBetween(Integer value1, Integer value2) {
            addCriterion("extension_account between", value1, value2, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("extension_account not between", value1, value2, "extensionAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountIsNull() {
            addCriterion("register_account is null");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountIsNotNull() {
            addCriterion("register_account is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountEqualTo(Integer value) {
            addCriterion("register_account =", value, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountNotEqualTo(Integer value) {
            addCriterion("register_account <>", value, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountGreaterThan(Integer value) {
            addCriterion("register_account >", value, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("register_account >=", value, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountLessThan(Integer value) {
            addCriterion("register_account <", value, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountLessThanOrEqualTo(Integer value) {
            addCriterion("register_account <=", value, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountIn(List<Integer> values) {
            addCriterion("register_account in", values, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountNotIn(List<Integer> values) {
            addCriterion("register_account not in", values, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountBetween(Integer value1, Integer value2) {
            addCriterion("register_account between", value1, value2, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andRegisterAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("register_account not between", value1, value2, "registerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountIsNull() {
            addCriterion("volunteer_account is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountIsNotNull() {
            addCriterion("volunteer_account is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountEqualTo(Integer value) {
            addCriterion("volunteer_account =", value, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountNotEqualTo(Integer value) {
            addCriterion("volunteer_account <>", value, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountGreaterThan(Integer value) {
            addCriterion("volunteer_account >", value, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("volunteer_account >=", value, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountLessThan(Integer value) {
            addCriterion("volunteer_account <", value, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountLessThanOrEqualTo(Integer value) {
            addCriterion("volunteer_account <=", value, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountIn(List<Integer> values) {
            addCriterion("volunteer_account in", values, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountNotIn(List<Integer> values) {
            addCriterion("volunteer_account not in", values, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountBetween(Integer value1, Integer value2) {
            addCriterion("volunteer_account between", value1, value2, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("volunteer_account not between", value1, value2, "volunteerAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountIsNull() {
            addCriterion("consult_account is null");
            return (Criteria) this;
        }

        public Criteria andConsultAccountIsNotNull() {
            addCriterion("consult_account is not null");
            return (Criteria) this;
        }

        public Criteria andConsultAccountEqualTo(Integer value) {
            addCriterion("consult_account =", value, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountNotEqualTo(Integer value) {
            addCriterion("consult_account <>", value, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountGreaterThan(Integer value) {
            addCriterion("consult_account >", value, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountGreaterThanOrEqualTo(Integer value) {
            addCriterion("consult_account >=", value, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountLessThan(Integer value) {
            addCriterion("consult_account <", value, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountLessThanOrEqualTo(Integer value) {
            addCriterion("consult_account <=", value, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountIn(List<Integer> values) {
            addCriterion("consult_account in", values, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountNotIn(List<Integer> values) {
            addCriterion("consult_account not in", values, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountBetween(Integer value1, Integer value2) {
            addCriterion("consult_account between", value1, value2, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andConsultAccountNotBetween(Integer value1, Integer value2) {
            addCriterion("consult_account not between", value1, value2, "consultAccount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountIsNull() {
            addCriterion("extension_amount is null");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountIsNotNull() {
            addCriterion("extension_amount is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountEqualTo(BigDecimal value) {
            addCriterion("extension_amount =", value, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountNotEqualTo(BigDecimal value) {
            addCriterion("extension_amount <>", value, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountGreaterThan(BigDecimal value) {
            addCriterion("extension_amount >", value, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("extension_amount >=", value, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountLessThan(BigDecimal value) {
            addCriterion("extension_amount <", value, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("extension_amount <=", value, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountIn(List<BigDecimal> values) {
            addCriterion("extension_amount in", values, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountNotIn(List<BigDecimal> values) {
            addCriterion("extension_amount not in", values, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("extension_amount between", value1, value2, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andExtensionAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("extension_amount not between", value1, value2, "extensionAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountIsNull() {
            addCriterion("volunteer_amount is null");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountIsNotNull() {
            addCriterion("volunteer_amount is not null");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountEqualTo(BigDecimal value) {
            addCriterion("volunteer_amount =", value, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountNotEqualTo(BigDecimal value) {
            addCriterion("volunteer_amount <>", value, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountGreaterThan(BigDecimal value) {
            addCriterion("volunteer_amount >", value, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("volunteer_amount >=", value, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountLessThan(BigDecimal value) {
            addCriterion("volunteer_amount <", value, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("volunteer_amount <=", value, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountIn(List<BigDecimal> values) {
            addCriterion("volunteer_amount in", values, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountNotIn(List<BigDecimal> values) {
            addCriterion("volunteer_amount not in", values, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("volunteer_amount between", value1, value2, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andVolunteerAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("volunteer_amount not between", value1, value2, "volunteerAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountIsNull() {
            addCriterion("consult_amount is null");
            return (Criteria) this;
        }

        public Criteria andConsultAmountIsNotNull() {
            addCriterion("consult_amount is not null");
            return (Criteria) this;
        }

        public Criteria andConsultAmountEqualTo(BigDecimal value) {
            addCriterion("consult_amount =", value, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountNotEqualTo(BigDecimal value) {
            addCriterion("consult_amount <>", value, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountGreaterThan(BigDecimal value) {
            addCriterion("consult_amount >", value, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("consult_amount >=", value, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountLessThan(BigDecimal value) {
            addCriterion("consult_amount <", value, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("consult_amount <=", value, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountIn(List<BigDecimal> values) {
            addCriterion("consult_amount in", values, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountNotIn(List<BigDecimal> values) {
            addCriterion("consult_amount not in", values, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consult_amount between", value1, value2, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andConsultAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("consult_amount not between", value1, value2, "consultAmount");
            return (Criteria) this;
        }

        public Criteria andUnionStrIsNull() {
            addCriterion("union_str is null");
            return (Criteria) this;
        }

        public Criteria andUnionStrIsNotNull() {
            addCriterion("union_str is not null");
            return (Criteria) this;
        }

        public Criteria andUnionStrEqualTo(String value) {
            addCriterion("union_str =", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrNotEqualTo(String value) {
            addCriterion("union_str <>", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrGreaterThan(String value) {
            addCriterion("union_str >", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrGreaterThanOrEqualTo(String value) {
            addCriterion("union_str >=", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrLessThan(String value) {
            addCriterion("union_str <", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrLessThanOrEqualTo(String value) {
            addCriterion("union_str <=", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrLike(String value) {
            addCriterion("union_str like", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrNotLike(String value) {
            addCriterion("union_str not like", value, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrIn(List<String> values) {
            addCriterion("union_str in", values, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrNotIn(List<String> values) {
            addCriterion("union_str not in", values, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrBetween(String value1, String value2) {
            addCriterion("union_str between", value1, value2, "unionStr");
            return (Criteria) this;
        }

        public Criteria andUnionStrNotBetween(String value1, String value2) {
            addCriterion("union_str not between", value1, value2, "unionStr");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendIsNull() {
            addCriterion("remark_extend is null");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendIsNotNull() {
            addCriterion("remark_extend is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendEqualTo(String value) {
            addCriterion("remark_extend =", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendNotEqualTo(String value) {
            addCriterion("remark_extend <>", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendGreaterThan(String value) {
            addCriterion("remark_extend >", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendGreaterThanOrEqualTo(String value) {
            addCriterion("remark_extend >=", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendLessThan(String value) {
            addCriterion("remark_extend <", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendLessThanOrEqualTo(String value) {
            addCriterion("remark_extend <=", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendLike(String value) {
            addCriterion("remark_extend like", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendNotLike(String value) {
            addCriterion("remark_extend not like", value, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendIn(List<String> values) {
            addCriterion("remark_extend in", values, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendNotIn(List<String> values) {
            addCriterion("remark_extend not in", values, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendBetween(String value1, String value2) {
            addCriterion("remark_extend between", value1, value2, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andRemarkExtendNotBetween(String value1, String value2) {
            addCriterion("remark_extend not between", value1, value2, "remarkExtend");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proxy_config_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table proxy_config_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}