package com.deao.dal.daomain.auto;

import java.math.BigDecimal;
import java.util.Date;

public class ProxyTradeRecordModel {
    /**
     * id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 用户userid
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * 交易记录类型
     *
     * @mbggenerated
     */
    private String tradeRecordType;

    /**
     * 交易记录类型值
     *
     * @mbggenerated
     */
    private String tradeRecordTypeValues;

    /**
     * 交易金额
     *
     * @mbggenerated
     */
    private BigDecimal tradeAmount;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.id
     *
     * @return the value of proxy_trade_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.id
     *
     * @param id the value for proxy_trade_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.user_id
     *
     * @return the value of proxy_trade_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.user_id
     *
     * @param userId the value for proxy_trade_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.trade_record_type
     *
     * @return the value of proxy_trade_record.trade_record_type
     *
     * @mbggenerated
     */
    public String getTradeRecordType() {
        return tradeRecordType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.trade_record_type
     *
     * @param tradeRecordType the value for proxy_trade_record.trade_record_type
     *
     * @mbggenerated
     */
    public void setTradeRecordType(String tradeRecordType) {
        this.tradeRecordType = tradeRecordType == null ? null : tradeRecordType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.trade_record_type_values
     *
     * @return the value of proxy_trade_record.trade_record_type_values
     *
     * @mbggenerated
     */
    public String getTradeRecordTypeValues() {
        return tradeRecordTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.trade_record_type_values
     *
     * @param tradeRecordTypeValues the value for proxy_trade_record.trade_record_type_values
     *
     * @mbggenerated
     */
    public void setTradeRecordTypeValues(String tradeRecordTypeValues) {
        this.tradeRecordTypeValues = tradeRecordTypeValues == null ? null : tradeRecordTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.trade_amount
     *
     * @return the value of proxy_trade_record.trade_amount
     *
     * @mbggenerated
     */
    public BigDecimal getTradeAmount() {
        return tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.trade_amount
     *
     * @param tradeAmount the value for proxy_trade_record.trade_amount
     *
     * @mbggenerated
     */
    public void setTradeAmount(BigDecimal tradeAmount) {
        this.tradeAmount = tradeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.remark
     *
     * @return the value of proxy_trade_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.remark
     *
     * @param remark the value for proxy_trade_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.remark_extend
     *
     * @return the value of proxy_trade_record.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.remark_extend
     *
     * @param remarkExtend the value for proxy_trade_record.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.create_time
     *
     * @return the value of proxy_trade_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.create_time
     *
     * @param createTime the value for proxy_trade_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.update_time
     *
     * @return the value of proxy_trade_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.update_time
     *
     * @param updateTime the value for proxy_trade_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_trade_record.is_delete
     *
     * @return the value of proxy_trade_record.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_trade_record.is_delete
     *
     * @param isDelete the value for proxy_trade_record.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}