package com.deao.dal.daomain.auto;

import java.util.Date;

public class ProxyUserDetailModel {
    /**
     * id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 代理id
     *
     * @mbggenerated
     */
    private Integer proxyId;

    /**
     * 代理名称
     *
     * @mbggenerated
     */
    private String proxyName;

    /**
     * 用户的唯一标识
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * unionid
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * 用户昵称
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * 用户的性别
     *
     * @mbggenerated
     */
    private String sex;

    /**
     * 用户头像
     *
     * @mbggenerated
     */
    private String headimgurl;

    /**
     * 省
     *
     * @mbggenerated
     */
    private String province;

    /**
     * 市
     *
     * @mbggenerated
     */
    private String city;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.id
     *
     * @return the value of proxy_user_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.id
     *
     * @param id the value for proxy_user_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.proxy_id
     *
     * @return the value of proxy_user_detail.proxy_id
     *
     * @mbggenerated
     */
    public Integer getProxyId() {
        return proxyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.proxy_id
     *
     * @param proxyId the value for proxy_user_detail.proxy_id
     *
     * @mbggenerated
     */
    public void setProxyId(Integer proxyId) {
        this.proxyId = proxyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.proxy_name
     *
     * @return the value of proxy_user_detail.proxy_name
     *
     * @mbggenerated
     */
    public String getProxyName() {
        return proxyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.proxy_name
     *
     * @param proxyName the value for proxy_user_detail.proxy_name
     *
     * @mbggenerated
     */
    public void setProxyName(String proxyName) {
        this.proxyName = proxyName == null ? null : proxyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.openid
     *
     * @return the value of proxy_user_detail.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.openid
     *
     * @param openid the value for proxy_user_detail.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.unionid
     *
     * @return the value of proxy_user_detail.unionid
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.unionid
     *
     * @param unionid the value for proxy_user_detail.unionid
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.nickname
     *
     * @return the value of proxy_user_detail.nickname
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.nickname
     *
     * @param nickname the value for proxy_user_detail.nickname
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.sex
     *
     * @return the value of proxy_user_detail.sex
     *
     * @mbggenerated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.sex
     *
     * @param sex the value for proxy_user_detail.sex
     *
     * @mbggenerated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.headimgurl
     *
     * @return the value of proxy_user_detail.headimgurl
     *
     * @mbggenerated
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.headimgurl
     *
     * @param headimgurl the value for proxy_user_detail.headimgurl
     *
     * @mbggenerated
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.province
     *
     * @return the value of proxy_user_detail.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.province
     *
     * @param province the value for proxy_user_detail.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.city
     *
     * @return the value of proxy_user_detail.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.city
     *
     * @param city the value for proxy_user_detail.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.remark
     *
     * @return the value of proxy_user_detail.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.remark
     *
     * @param remark the value for proxy_user_detail.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.remark_extend
     *
     * @return the value of proxy_user_detail.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.remark_extend
     *
     * @param remarkExtend the value for proxy_user_detail.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.create_time
     *
     * @return the value of proxy_user_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.create_time
     *
     * @param createTime the value for proxy_user_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.update_time
     *
     * @return the value of proxy_user_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.update_time
     *
     * @param updateTime the value for proxy_user_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proxy_user_detail.is_delete
     *
     * @return the value of proxy_user_detail.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proxy_user_detail.is_delete
     *
     * @param isDelete the value for proxy_user_detail.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}