package com.deao.dal.daomain.auto;

import java.util.Date;

public class RecruitPlanModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 计划no
     *
     * @mbggenerated
     */
    private String planNo;

    /**
     * 年份
     *
     * @mbggenerated
     */
    private String year;

    /**
     * 学校id
     *
     * @mbggenerated
     */
    private Integer schoolId;

    /**
     * 专业id
     *
     * @mbggenerated
     */
    private Integer majorId;

    /**
     * 专业代码
     *
     * @mbggenerated
     */
    private String majorCode;

    /**
     * 招生人数
     *
     * @mbggenerated
     */
    private Integer recruitCount;

    /**
     * 录取分数
     *
     * @mbggenerated
     */
    private Integer recruitNumber;

    /**
     * 排序[数字越小越靠前]
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * 限报条件
     *
     * @mbggenerated
     */
    private String reportingConditions;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.id
     *
     * @return the value of recruit_plan.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.id
     *
     * @param id the value for recruit_plan.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.plan_no
     *
     * @return the value of recruit_plan.plan_no
     *
     * @mbggenerated
     */
    public String getPlanNo() {
        return planNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.plan_no
     *
     * @param planNo the value for recruit_plan.plan_no
     *
     * @mbggenerated
     */
    public void setPlanNo(String planNo) {
        this.planNo = planNo == null ? null : planNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.year
     *
     * @return the value of recruit_plan.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.year
     *
     * @param year the value for recruit_plan.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.school_id
     *
     * @return the value of recruit_plan.school_id
     *
     * @mbggenerated
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.school_id
     *
     * @param schoolId the value for recruit_plan.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.major_id
     *
     * @return the value of recruit_plan.major_id
     *
     * @mbggenerated
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.major_id
     *
     * @param majorId the value for recruit_plan.major_id
     *
     * @mbggenerated
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.major_code
     *
     * @return the value of recruit_plan.major_code
     *
     * @mbggenerated
     */
    public String getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.major_code
     *
     * @param majorCode the value for recruit_plan.major_code
     *
     * @mbggenerated
     */
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode == null ? null : majorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.recruit_count
     *
     * @return the value of recruit_plan.recruit_count
     *
     * @mbggenerated
     */
    public Integer getRecruitCount() {
        return recruitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.recruit_count
     *
     * @param recruitCount the value for recruit_plan.recruit_count
     *
     * @mbggenerated
     */
    public void setRecruitCount(Integer recruitCount) {
        this.recruitCount = recruitCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.recruit_number
     *
     * @return the value of recruit_plan.recruit_number
     *
     * @mbggenerated
     */
    public Integer getRecruitNumber() {
        return recruitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.recruit_number
     *
     * @param recruitNumber the value for recruit_plan.recruit_number
     *
     * @mbggenerated
     */
    public void setRecruitNumber(Integer recruitNumber) {
        this.recruitNumber = recruitNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.sort
     *
     * @return the value of recruit_plan.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.sort
     *
     * @param sort the value for recruit_plan.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.reporting_conditions
     *
     * @return the value of recruit_plan.reporting_conditions
     *
     * @mbggenerated
     */
    public String getReportingConditions() {
        return reportingConditions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.reporting_conditions
     *
     * @param reportingConditions the value for recruit_plan.reporting_conditions
     *
     * @mbggenerated
     */
    public void setReportingConditions(String reportingConditions) {
        this.reportingConditions = reportingConditions == null ? null : reportingConditions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.remark
     *
     * @return the value of recruit_plan.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.remark
     *
     * @param remark the value for recruit_plan.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.remark_extend
     *
     * @return the value of recruit_plan.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.remark_extend
     *
     * @param remarkExtend the value for recruit_plan.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.create_time
     *
     * @return the value of recruit_plan.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.create_time
     *
     * @param createTime the value for recruit_plan.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.update_time
     *
     * @return the value of recruit_plan.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.update_time
     *
     * @param updateTime the value for recruit_plan.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_plan.is_delete
     *
     * @return the value of recruit_plan.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_plan.is_delete
     *
     * @param isDelete the value for recruit_plan.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}