package com.deao.dal.daomain.auto;

import java.util.Date;

public class SysTaskRecordModel {
    /**
     * id
     *
     * @mbggenerated
     */
    private Byte id;

    /**
     * 定时任务枚举
     *
     * @mbggenerated
     */
    private String taskName;

    /**
     * 定时任务枚举值
     *
     * @mbggenerated
     */
    private String taskNameValue;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.id
     *
     * @return the value of sys_task_record.id
     *
     * @mbggenerated
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.id
     *
     * @param id the value for sys_task_record.id
     *
     * @mbggenerated
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.task_name
     *
     * @return the value of sys_task_record.task_name
     *
     * @mbggenerated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.task_name
     *
     * @param taskName the value for sys_task_record.task_name
     *
     * @mbggenerated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.task_name_value
     *
     * @return the value of sys_task_record.task_name_value
     *
     * @mbggenerated
     */
    public String getTaskNameValue() {
        return taskNameValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.task_name_value
     *
     * @param taskNameValue the value for sys_task_record.task_name_value
     *
     * @mbggenerated
     */
    public void setTaskNameValue(String taskNameValue) {
        this.taskNameValue = taskNameValue == null ? null : taskNameValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.remark
     *
     * @return the value of sys_task_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.remark
     *
     * @param remark the value for sys_task_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.remark_extend
     *
     * @return the value of sys_task_record.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.remark_extend
     *
     * @param remarkExtend the value for sys_task_record.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.create_time
     *
     * @return the value of sys_task_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.create_time
     *
     * @param createTime the value for sys_task_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.update_time
     *
     * @return the value of sys_task_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.update_time
     *
     * @param updateTime the value for sys_task_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_task_record.is_delete
     *
     * @return the value of sys_task_record.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_task_record.is_delete
     *
     * @param isDelete the value for sys_task_record.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}