package com.deao.dal.daomain.auto;

import java.math.BigDecimal;
import java.util.Date;

public class SystemBasicConfigModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 支付价格
     *
     * @mbggenerated
     */
    private BigDecimal payPrice;

    /**
     * 模拟志愿底牌价格
     *
     * @mbggenerated
     */
    private BigDecimal cardPayPrice;

    /**
     * 数字1:注册用户数
     *
     * @mbggenerated
     */
    private Integer count1;

    /**
     * 数字2:已填报的次数
     *
     * @mbggenerated
     */
    private Integer count2;

    /**
     * 数字3:已生成的草表
     *
     * @mbggenerated
     */
    private Integer count3;

    /**
     * 客服电话
     *
     * @mbggenerated
     */
    private String customerPhone;

    /**
     * 商户首次接单支付金额
     *
     * @mbggenerated
     */
    private BigDecimal merchantFirstPayamount;

    /**
     * 商户接单支付金额
     *
     * @mbggenerated
     */
    private BigDecimal merchantPayamount;

    /**
     * 志愿推送分数换算比率
     *
     * @mbggenerated
     */
    private BigDecimal conversionRatio;

    /**
     * 真实志愿底牌价格
     *
     * @mbggenerated
     */
    private BigDecimal realCardPayPrice;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * 代理的提成比例
     *
     * @mbggenerated
     */
    private BigDecimal proxyRatio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.id
     *
     * @return the value of system_basic_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.id
     *
     * @param id the value for system_basic_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.pay_price
     *
     * @return the value of system_basic_config.pay_price
     *
     * @mbggenerated
     */
    public BigDecimal getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.pay_price
     *
     * @param payPrice the value for system_basic_config.pay_price
     *
     * @mbggenerated
     */
    public void setPayPrice(BigDecimal payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.card_pay_price
     *
     * @return the value of system_basic_config.card_pay_price
     *
     * @mbggenerated
     */
    public BigDecimal getCardPayPrice() {
        return cardPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.card_pay_price
     *
     * @param cardPayPrice the value for system_basic_config.card_pay_price
     *
     * @mbggenerated
     */
    public void setCardPayPrice(BigDecimal cardPayPrice) {
        this.cardPayPrice = cardPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.count1
     *
     * @return the value of system_basic_config.count1
     *
     * @mbggenerated
     */
    public Integer getCount1() {
        return count1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.count1
     *
     * @param count1 the value for system_basic_config.count1
     *
     * @mbggenerated
     */
    public void setCount1(Integer count1) {
        this.count1 = count1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.count2
     *
     * @return the value of system_basic_config.count2
     *
     * @mbggenerated
     */
    public Integer getCount2() {
        return count2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.count2
     *
     * @param count2 the value for system_basic_config.count2
     *
     * @mbggenerated
     */
    public void setCount2(Integer count2) {
        this.count2 = count2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.count3
     *
     * @return the value of system_basic_config.count3
     *
     * @mbggenerated
     */
    public Integer getCount3() {
        return count3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.count3
     *
     * @param count3 the value for system_basic_config.count3
     *
     * @mbggenerated
     */
    public void setCount3(Integer count3) {
        this.count3 = count3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.customer_phone
     *
     * @return the value of system_basic_config.customer_phone
     *
     * @mbggenerated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.customer_phone
     *
     * @param customerPhone the value for system_basic_config.customer_phone
     *
     * @mbggenerated
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone == null ? null : customerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.merchant_first_payamount
     *
     * @return the value of system_basic_config.merchant_first_payamount
     *
     * @mbggenerated
     */
    public BigDecimal getMerchantFirstPayamount() {
        return merchantFirstPayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.merchant_first_payamount
     *
     * @param merchantFirstPayamount the value for system_basic_config.merchant_first_payamount
     *
     * @mbggenerated
     */
    public void setMerchantFirstPayamount(BigDecimal merchantFirstPayamount) {
        this.merchantFirstPayamount = merchantFirstPayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.merchant_payamount
     *
     * @return the value of system_basic_config.merchant_payamount
     *
     * @mbggenerated
     */
    public BigDecimal getMerchantPayamount() {
        return merchantPayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.merchant_payamount
     *
     * @param merchantPayamount the value for system_basic_config.merchant_payamount
     *
     * @mbggenerated
     */
    public void setMerchantPayamount(BigDecimal merchantPayamount) {
        this.merchantPayamount = merchantPayamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.conversion_ratio
     *
     * @return the value of system_basic_config.conversion_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getConversionRatio() {
        return conversionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.conversion_ratio
     *
     * @param conversionRatio the value for system_basic_config.conversion_ratio
     *
     * @mbggenerated
     */
    public void setConversionRatio(BigDecimal conversionRatio) {
        this.conversionRatio = conversionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.real_card_pay_price
     *
     * @return the value of system_basic_config.real_card_pay_price
     *
     * @mbggenerated
     */
    public BigDecimal getRealCardPayPrice() {
        return realCardPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.real_card_pay_price
     *
     * @param realCardPayPrice the value for system_basic_config.real_card_pay_price
     *
     * @mbggenerated
     */
    public void setRealCardPayPrice(BigDecimal realCardPayPrice) {
        this.realCardPayPrice = realCardPayPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.remark
     *
     * @return the value of system_basic_config.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.remark
     *
     * @param remark the value for system_basic_config.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.create_time
     *
     * @return the value of system_basic_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.create_time
     *
     * @param createTime the value for system_basic_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.update_time
     *
     * @return the value of system_basic_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.update_time
     *
     * @param updateTime the value for system_basic_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.is_delete
     *
     * @return the value of system_basic_config.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.is_delete
     *
     * @param isDelete the value for system_basic_config.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_basic_config.proxy_ratio
     *
     * @return the value of system_basic_config.proxy_ratio
     *
     * @mbggenerated
     */
    public BigDecimal getProxyRatio() {
        return proxyRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_basic_config.proxy_ratio
     *
     * @param proxyRatio the value for system_basic_config.proxy_ratio
     *
     * @mbggenerated
     */
    public void setProxyRatio(BigDecimal proxyRatio) {
        this.proxyRatio = proxyRatio;
    }
}