package com.deao.dal.daomain.auto;

import java.util.Date;

public class SystemSearchRecordModel {
    /**
     * id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 用户userid
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * 搜索类型
     *
     * @mbggenerated
     */
    private String searchType;

    /**
     * 搜索类型值[学校,专业]
     *
     * @mbggenerated
     */
    private String searchTypeValues;

    /**
     * 搜索方式
     *
     * @mbggenerated
     */
    private String searchMode;

    /**
     * 搜索方式值[用户主动,热搜]
     *
     * @mbggenerated
     */
    private String searchModeValues;

    /**
     * 记录id
     *
     * @mbggenerated
     */
    private String recordId;

    /**
     * 记录名字
     *
     * @mbggenerated
     */
    private String recordName;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.id
     *
     * @return the value of system_search_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.id
     *
     * @param id the value for system_search_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.user_id
     *
     * @return the value of system_search_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.user_id
     *
     * @param userId the value for system_search_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.search_type
     *
     * @return the value of system_search_record.search_type
     *
     * @mbggenerated
     */
    public String getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.search_type
     *
     * @param searchType the value for system_search_record.search_type
     *
     * @mbggenerated
     */
    public void setSearchType(String searchType) {
        this.searchType = searchType == null ? null : searchType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.search_type_values
     *
     * @return the value of system_search_record.search_type_values
     *
     * @mbggenerated
     */
    public String getSearchTypeValues() {
        return searchTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.search_type_values
     *
     * @param searchTypeValues the value for system_search_record.search_type_values
     *
     * @mbggenerated
     */
    public void setSearchTypeValues(String searchTypeValues) {
        this.searchTypeValues = searchTypeValues == null ? null : searchTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.search_mode
     *
     * @return the value of system_search_record.search_mode
     *
     * @mbggenerated
     */
    public String getSearchMode() {
        return searchMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.search_mode
     *
     * @param searchMode the value for system_search_record.search_mode
     *
     * @mbggenerated
     */
    public void setSearchMode(String searchMode) {
        this.searchMode = searchMode == null ? null : searchMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.search_mode_values
     *
     * @return the value of system_search_record.search_mode_values
     *
     * @mbggenerated
     */
    public String getSearchModeValues() {
        return searchModeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.search_mode_values
     *
     * @param searchModeValues the value for system_search_record.search_mode_values
     *
     * @mbggenerated
     */
    public void setSearchModeValues(String searchModeValues) {
        this.searchModeValues = searchModeValues == null ? null : searchModeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.record_id
     *
     * @return the value of system_search_record.record_id
     *
     * @mbggenerated
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.record_id
     *
     * @param recordId the value for system_search_record.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.record_name
     *
     * @return the value of system_search_record.record_name
     *
     * @mbggenerated
     */
    public String getRecordName() {
        return recordName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.record_name
     *
     * @param recordName the value for system_search_record.record_name
     *
     * @mbggenerated
     */
    public void setRecordName(String recordName) {
        this.recordName = recordName == null ? null : recordName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.remark
     *
     * @return the value of system_search_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.remark
     *
     * @param remark the value for system_search_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.remark_extend
     *
     * @return the value of system_search_record.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.remark_extend
     *
     * @param remarkExtend the value for system_search_record.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.create_time
     *
     * @return the value of system_search_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.create_time
     *
     * @param createTime the value for system_search_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.update_time
     *
     * @return the value of system_search_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.update_time
     *
     * @param updateTime the value for system_search_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_search_record.is_delete
     *
     * @return the value of system_search_record.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_search_record.is_delete
     *
     * @param isDelete the value for system_search_record.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}