package com.deao.dal.daomain.auto;

public class TaskInfoUserSearchModelWithBLOBs extends TaskInfoUserSearchModel {
    /**
     * 存查排名 基础信息
     *
     * @mbggenerated
     */
    private String searchMajor;

    /**
     * 存查排名 分数信息
     *
     * @mbggenerated
     */
    private String searchSchool;

    /**
     * 搜索信息
     *
     * @mbggenerated
     */
    private String searchInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info_user_search.search_major
     *
     * @return the value of task_info_user_search.search_major
     *
     * @mbggenerated
     */
    public String getSearchMajor() {
        return searchMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info_user_search.search_major
     *
     * @param searchMajor the value for task_info_user_search.search_major
     *
     * @mbggenerated
     */
    public void setSearchMajor(String searchMajor) {
        this.searchMajor = searchMajor == null ? null : searchMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info_user_search.search_school
     *
     * @return the value of task_info_user_search.search_school
     *
     * @mbggenerated
     */
    public String getSearchSchool() {
        return searchSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info_user_search.search_school
     *
     * @param searchSchool the value for task_info_user_search.search_school
     *
     * @mbggenerated
     */
    public void setSearchSchool(String searchSchool) {
        this.searchSchool = searchSchool == null ? null : searchSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_info_user_search.search_info
     *
     * @return the value of task_info_user_search.search_info
     *
     * @mbggenerated
     */
    public String getSearchInfo() {
        return searchInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_info_user_search.search_info
     *
     * @param searchInfo the value for task_info_user_search.search_info
     *
     * @mbggenerated
     */
    public void setSearchInfo(String searchInfo) {
        this.searchInfo = searchInfo == null ? null : searchInfo.trim();
    }
}