package com.deao.dal.daomain.auto;

import java.util.Date;

public class WechatChannelConfigModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 归属服务号
     *
     * @mbggenerated
     */
    private String serviceNumber;

    /**
     * 归属服务号的值
     *
     * @mbggenerated
     */
    private String serviceNumberValues;

    /**
     * 渠道名字
     *
     * @mbggenerated
     */
    private String channelName;

    /**
     * 渠道描述
     *
     * @mbggenerated
     */
    private String channelDescribe;

    /**
     * 渠道url
     *
     * @mbggenerated
     */
    private String channelUrl;

    /**
     * 渠道关注总人数
     *
     * @mbggenerated
     */
    private Integer channelAccount;

    /**
     * 渠道注册总人数
     *
     * @mbggenerated
     */
    private Integer channelRegisterAccount;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.id
     *
     * @return the value of wechat_channel_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.id
     *
     * @param id the value for wechat_channel_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.service_number
     *
     * @return the value of wechat_channel_config.service_number
     *
     * @mbggenerated
     */
    public String getServiceNumber() {
        return serviceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.service_number
     *
     * @param serviceNumber the value for wechat_channel_config.service_number
     *
     * @mbggenerated
     */
    public void setServiceNumber(String serviceNumber) {
        this.serviceNumber = serviceNumber == null ? null : serviceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.service_number_values
     *
     * @return the value of wechat_channel_config.service_number_values
     *
     * @mbggenerated
     */
    public String getServiceNumberValues() {
        return serviceNumberValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.service_number_values
     *
     * @param serviceNumberValues the value for wechat_channel_config.service_number_values
     *
     * @mbggenerated
     */
    public void setServiceNumberValues(String serviceNumberValues) {
        this.serviceNumberValues = serviceNumberValues == null ? null : serviceNumberValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.channel_name
     *
     * @return the value of wechat_channel_config.channel_name
     *
     * @mbggenerated
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.channel_name
     *
     * @param channelName the value for wechat_channel_config.channel_name
     *
     * @mbggenerated
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.channel_describe
     *
     * @return the value of wechat_channel_config.channel_describe
     *
     * @mbggenerated
     */
    public String getChannelDescribe() {
        return channelDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.channel_describe
     *
     * @param channelDescribe the value for wechat_channel_config.channel_describe
     *
     * @mbggenerated
     */
    public void setChannelDescribe(String channelDescribe) {
        this.channelDescribe = channelDescribe == null ? null : channelDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.channel_url
     *
     * @return the value of wechat_channel_config.channel_url
     *
     * @mbggenerated
     */
    public String getChannelUrl() {
        return channelUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.channel_url
     *
     * @param channelUrl the value for wechat_channel_config.channel_url
     *
     * @mbggenerated
     */
    public void setChannelUrl(String channelUrl) {
        this.channelUrl = channelUrl == null ? null : channelUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.channel_account
     *
     * @return the value of wechat_channel_config.channel_account
     *
     * @mbggenerated
     */
    public Integer getChannelAccount() {
        return channelAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.channel_account
     *
     * @param channelAccount the value for wechat_channel_config.channel_account
     *
     * @mbggenerated
     */
    public void setChannelAccount(Integer channelAccount) {
        this.channelAccount = channelAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.channel_register_account
     *
     * @return the value of wechat_channel_config.channel_register_account
     *
     * @mbggenerated
     */
    public Integer getChannelRegisterAccount() {
        return channelRegisterAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.channel_register_account
     *
     * @param channelRegisterAccount the value for wechat_channel_config.channel_register_account
     *
     * @mbggenerated
     */
    public void setChannelRegisterAccount(Integer channelRegisterAccount) {
        this.channelRegisterAccount = channelRegisterAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.remark
     *
     * @return the value of wechat_channel_config.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.remark
     *
     * @param remark the value for wechat_channel_config.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.remark_extend
     *
     * @return the value of wechat_channel_config.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.remark_extend
     *
     * @param remarkExtend the value for wechat_channel_config.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.create_time
     *
     * @return the value of wechat_channel_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.create_time
     *
     * @param createTime the value for wechat_channel_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.update_time
     *
     * @return the value of wechat_channel_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.update_time
     *
     * @param updateTime the value for wechat_channel_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_channel_config.is_delete
     *
     * @return the value of wechat_channel_config.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_channel_config.is_delete
     *
     * @param isDelete the value for wechat_channel_config.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}