package com.deao.dal.daomain.auto;

import java.util.Date;

public class WechatMemberVolunteerRecordModel {
    /**
     * id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 用户id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * 对应订单号
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * 学校id
     *
     * @mbggenerated
     */
    private String schoolId;

    /**
     * 专业代码
     *
     * @mbggenerated
     */
    private String majorCode;

    /**
     * 专业id
     *
     * @mbggenerated
     */
    private Integer majorId;

    /**
     * 年份（当前年份）
     *
     * @mbggenerated
     */
    private String year;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.id
     *
     * @return the value of wechat_member_volunteer_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.id
     *
     * @param id the value for wechat_member_volunteer_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.user_id
     *
     * @return the value of wechat_member_volunteer_record.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.user_id
     *
     * @param userId the value for wechat_member_volunteer_record.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.order_no
     *
     * @return the value of wechat_member_volunteer_record.order_no
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.order_no
     *
     * @param orderNo the value for wechat_member_volunteer_record.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.school_id
     *
     * @return the value of wechat_member_volunteer_record.school_id
     *
     * @mbggenerated
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.school_id
     *
     * @param schoolId the value for wechat_member_volunteer_record.school_id
     *
     * @mbggenerated
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId == null ? null : schoolId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.major_code
     *
     * @return the value of wechat_member_volunteer_record.major_code
     *
     * @mbggenerated
     */
    public String getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.major_code
     *
     * @param majorCode the value for wechat_member_volunteer_record.major_code
     *
     * @mbggenerated
     */
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode == null ? null : majorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.major_id
     *
     * @return the value of wechat_member_volunteer_record.major_id
     *
     * @mbggenerated
     */
    public Integer getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.major_id
     *
     * @param majorId the value for wechat_member_volunteer_record.major_id
     *
     * @mbggenerated
     */
    public void setMajorId(Integer majorId) {
        this.majorId = majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.year
     *
     * @return the value of wechat_member_volunteer_record.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.year
     *
     * @param year the value for wechat_member_volunteer_record.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.remark
     *
     * @return the value of wechat_member_volunteer_record.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.remark
     *
     * @param remark the value for wechat_member_volunteer_record.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.remark_extend
     *
     * @return the value of wechat_member_volunteer_record.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.remark_extend
     *
     * @param remarkExtend the value for wechat_member_volunteer_record.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.create_time
     *
     * @return the value of wechat_member_volunteer_record.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.create_time
     *
     * @param createTime the value for wechat_member_volunteer_record.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.update_time
     *
     * @return the value of wechat_member_volunteer_record.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.update_time
     *
     * @param updateTime the value for wechat_member_volunteer_record.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_volunteer_record.is_delete
     *
     * @return the value of wechat_member_volunteer_record.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_volunteer_record.is_delete
     *
     * @param isDelete the value for wechat_member_volunteer_record.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}