package com.deao.dal.daomain.auto;

import java.math.BigDecimal;
import java.util.Date;

public class WechatMemberAchievementModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 用户userid
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * 教育类型
     *
     * @mbggenerated
     */
    private String eduType;

    /**
     * 教育类型的值
     *
     * @mbggenerated
     */
    private String eduTypeValues;

    /**
     * 类别名字
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * 类别名字 总人数
     *
     * @mbggenerated
     */
    private String peopleTotal;

    /**
     * 用户填写 总分数
     *
     * @mbggenerated
     */
    private BigDecimal fractionTotal;

    /**
     * 计算出 总排名
     *
     * @mbggenerated
     */
    private String rankingTotal;

    /**
     * 年份
     *
     * @mbggenerated
     */
    private String year;

    /**
     * 备注 [ 存放本科专科字段 见枚举 EnumsEducationalLevel ]
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.id
     *
     * @return the value of wechat_member_achievement.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.id
     *
     * @param id the value for wechat_member_achievement.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.user_id
     *
     * @return the value of wechat_member_achievement.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.user_id
     *
     * @param userId the value for wechat_member_achievement.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.edu_type
     *
     * @return the value of wechat_member_achievement.edu_type
     *
     * @mbggenerated
     */
    public String getEduType() {
        return eduType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.edu_type
     *
     * @param eduType the value for wechat_member_achievement.edu_type
     *
     * @mbggenerated
     */
    public void setEduType(String eduType) {
        this.eduType = eduType == null ? null : eduType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.edu_type_values
     *
     * @return the value of wechat_member_achievement.edu_type_values
     *
     * @mbggenerated
     */
    public String getEduTypeValues() {
        return eduTypeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.edu_type_values
     *
     * @param eduTypeValues the value for wechat_member_achievement.edu_type_values
     *
     * @mbggenerated
     */
    public void setEduTypeValues(String eduTypeValues) {
        this.eduTypeValues = eduTypeValues == null ? null : eduTypeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.category_name
     *
     * @return the value of wechat_member_achievement.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.category_name
     *
     * @param categoryName the value for wechat_member_achievement.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.people_total
     *
     * @return the value of wechat_member_achievement.people_total
     *
     * @mbggenerated
     */
    public String getPeopleTotal() {
        return peopleTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.people_total
     *
     * @param peopleTotal the value for wechat_member_achievement.people_total
     *
     * @mbggenerated
     */
    public void setPeopleTotal(String peopleTotal) {
        this.peopleTotal = peopleTotal == null ? null : peopleTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.fraction_total
     *
     * @return the value of wechat_member_achievement.fraction_total
     *
     * @mbggenerated
     */
    public BigDecimal getFractionTotal() {
        return fractionTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.fraction_total
     *
     * @param fractionTotal the value for wechat_member_achievement.fraction_total
     *
     * @mbggenerated
     */
    public void setFractionTotal(BigDecimal fractionTotal) {
        this.fractionTotal = fractionTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.ranking_total
     *
     * @return the value of wechat_member_achievement.ranking_total
     *
     * @mbggenerated
     */
    public String getRankingTotal() {
        return rankingTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.ranking_total
     *
     * @param rankingTotal the value for wechat_member_achievement.ranking_total
     *
     * @mbggenerated
     */
    public void setRankingTotal(String rankingTotal) {
        this.rankingTotal = rankingTotal == null ? null : rankingTotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.year
     *
     * @return the value of wechat_member_achievement.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.year
     *
     * @param year the value for wechat_member_achievement.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.remark
     *
     * @return the value of wechat_member_achievement.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.remark
     *
     * @param remark the value for wechat_member_achievement.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.remark_extend
     *
     * @return the value of wechat_member_achievement.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.remark_extend
     *
     * @param remarkExtend the value for wechat_member_achievement.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.create_time
     *
     * @return the value of wechat_member_achievement.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.create_time
     *
     * @param createTime the value for wechat_member_achievement.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.update_time
     *
     * @return the value of wechat_member_achievement.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.update_time
     *
     * @param updateTime the value for wechat_member_achievement.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_member_achievement.is_delete
     *
     * @return the value of wechat_member_achievement.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_member_achievement.is_delete
     *
     * @param isDelete the value for wechat_member_achievement.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}