package com.deao.dal.daomain.auto;

import java.util.Date;

public class ZhaobanStuFollowModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 学生ID,uuid
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * N否   Y是
     *
     * @mbggenerated
     */
    private String isPrepay;

    /**
     * 缴费金额
     *
     * @mbggenerated
     */
    private Long payMoney;

    /**
     * 缴费日期
     *
     * @mbggenerated
     */
    private Date payTime;

    /**
     * 通知书情况
     *
     * @mbggenerated
     */
    private String notice;

    /**
     * 通知书情况的值
     *
     * @mbggenerated
     */
    private String noticeValues;

    /**
     * 就读意愿
     *
     * @mbggenerated
     */
    private String studyWish;

    /**
     * 就读意愿的值
     *
     * @mbggenerated
     */
    private String studyWishValues;

    /**
     * 现在情况
     *
     * @mbggenerated
     */
    private String nowCondition;

    /**
     * 现在情况的值
     *
     * @mbggenerated
     */
    private String nowConditionValues;

    /**
     * 跟进时间
     *
     * @mbggenerated
     */
    private Date followupTime;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.id
     *
     * @return the value of zhaoban_stu_follow.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.id
     *
     * @param id the value for zhaoban_stu_follow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.stu_id
     *
     * @return the value of zhaoban_stu_follow.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.stu_id
     *
     * @param stuId the value for zhaoban_stu_follow.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.is_prepay
     *
     * @return the value of zhaoban_stu_follow.is_prepay
     *
     * @mbggenerated
     */
    public String getIsPrepay() {
        return isPrepay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.is_prepay
     *
     * @param isPrepay the value for zhaoban_stu_follow.is_prepay
     *
     * @mbggenerated
     */
    public void setIsPrepay(String isPrepay) {
        this.isPrepay = isPrepay == null ? null : isPrepay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.pay_money
     *
     * @return the value of zhaoban_stu_follow.pay_money
     *
     * @mbggenerated
     */
    public Long getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.pay_money
     *
     * @param payMoney the value for zhaoban_stu_follow.pay_money
     *
     * @mbggenerated
     */
    public void setPayMoney(Long payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.pay_time
     *
     * @return the value of zhaoban_stu_follow.pay_time
     *
     * @mbggenerated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.pay_time
     *
     * @param payTime the value for zhaoban_stu_follow.pay_time
     *
     * @mbggenerated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.notice
     *
     * @return the value of zhaoban_stu_follow.notice
     *
     * @mbggenerated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.notice
     *
     * @param notice the value for zhaoban_stu_follow.notice
     *
     * @mbggenerated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.notice_values
     *
     * @return the value of zhaoban_stu_follow.notice_values
     *
     * @mbggenerated
     */
    public String getNoticeValues() {
        return noticeValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.notice_values
     *
     * @param noticeValues the value for zhaoban_stu_follow.notice_values
     *
     * @mbggenerated
     */
    public void setNoticeValues(String noticeValues) {
        this.noticeValues = noticeValues == null ? null : noticeValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.study_wish
     *
     * @return the value of zhaoban_stu_follow.study_wish
     *
     * @mbggenerated
     */
    public String getStudyWish() {
        return studyWish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.study_wish
     *
     * @param studyWish the value for zhaoban_stu_follow.study_wish
     *
     * @mbggenerated
     */
    public void setStudyWish(String studyWish) {
        this.studyWish = studyWish == null ? null : studyWish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.study_wish_values
     *
     * @return the value of zhaoban_stu_follow.study_wish_values
     *
     * @mbggenerated
     */
    public String getStudyWishValues() {
        return studyWishValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.study_wish_values
     *
     * @param studyWishValues the value for zhaoban_stu_follow.study_wish_values
     *
     * @mbggenerated
     */
    public void setStudyWishValues(String studyWishValues) {
        this.studyWishValues = studyWishValues == null ? null : studyWishValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.now_condition
     *
     * @return the value of zhaoban_stu_follow.now_condition
     *
     * @mbggenerated
     */
    public String getNowCondition() {
        return nowCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.now_condition
     *
     * @param nowCondition the value for zhaoban_stu_follow.now_condition
     *
     * @mbggenerated
     */
    public void setNowCondition(String nowCondition) {
        this.nowCondition = nowCondition == null ? null : nowCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.now_condition_values
     *
     * @return the value of zhaoban_stu_follow.now_condition_values
     *
     * @mbggenerated
     */
    public String getNowConditionValues() {
        return nowConditionValues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.now_condition_values
     *
     * @param nowConditionValues the value for zhaoban_stu_follow.now_condition_values
     *
     * @mbggenerated
     */
    public void setNowConditionValues(String nowConditionValues) {
        this.nowConditionValues = nowConditionValues == null ? null : nowConditionValues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.followup_time
     *
     * @return the value of zhaoban_stu_follow.followup_time
     *
     * @mbggenerated
     */
    public Date getFollowupTime() {
        return followupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.followup_time
     *
     * @param followupTime the value for zhaoban_stu_follow.followup_time
     *
     * @mbggenerated
     */
    public void setFollowupTime(Date followupTime) {
        this.followupTime = followupTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.remark
     *
     * @return the value of zhaoban_stu_follow.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.remark
     *
     * @param remark the value for zhaoban_stu_follow.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.remark_extend
     *
     * @return the value of zhaoban_stu_follow.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.remark_extend
     *
     * @param remarkExtend the value for zhaoban_stu_follow.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.create_time
     *
     * @return the value of zhaoban_stu_follow.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.create_time
     *
     * @param createTime the value for zhaoban_stu_follow.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.update_time
     *
     * @return the value of zhaoban_stu_follow.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.update_time
     *
     * @param updateTime the value for zhaoban_stu_follow.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_stu_follow.is_delete
     *
     * @return the value of zhaoban_stu_follow.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_stu_follow.is_delete
     *
     * @param isDelete the value for zhaoban_stu_follow.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}