package com.deao.dal.daomain.auto;

import java.util.Date;

public class ZhaobanTeacherInfoModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 姓名
     *
     * @mbggenerated
     */
    private String name;

    /**
     * 手机号
     *
     * @mbggenerated
     */
    private String bindPhone;

    /**
     * openId
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.id
     *
     * @return the value of zhaoban_teacher_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.id
     *
     * @param id the value for zhaoban_teacher_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.name
     *
     * @return the value of zhaoban_teacher_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.name
     *
     * @param name the value for zhaoban_teacher_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.bind_phone
     *
     * @return the value of zhaoban_teacher_info.bind_phone
     *
     * @mbggenerated
     */
    public String getBindPhone() {
        return bindPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.bind_phone
     *
     * @param bindPhone the value for zhaoban_teacher_info.bind_phone
     *
     * @mbggenerated
     */
    public void setBindPhone(String bindPhone) {
        this.bindPhone = bindPhone == null ? null : bindPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.openid
     *
     * @return the value of zhaoban_teacher_info.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.openid
     *
     * @param openid the value for zhaoban_teacher_info.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.remark
     *
     * @return the value of zhaoban_teacher_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.remark
     *
     * @param remark the value for zhaoban_teacher_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.remark_extend
     *
     * @return the value of zhaoban_teacher_info.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.remark_extend
     *
     * @param remarkExtend the value for zhaoban_teacher_info.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.create_time
     *
     * @return the value of zhaoban_teacher_info.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.create_time
     *
     * @param createTime the value for zhaoban_teacher_info.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.update_time
     *
     * @return the value of zhaoban_teacher_info.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.update_time
     *
     * @param updateTime the value for zhaoban_teacher_info.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_teacher_info.is_delete
     *
     * @return the value of zhaoban_teacher_info.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_teacher_info.is_delete
     *
     * @param isDelete the value for zhaoban_teacher_info.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}