package com.deao.dal.daomain.auto;

import java.util.Date;

public class ZhaobanUserStudentModel {
    /**
     * 
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * 管理用户ID
     *
     * @mbggenerated
     */
    private String adminUserId;

    /**
     * 学生ID,uuid
     *
     * @mbggenerated
     */
    private String stuId;

    /**
     * 0 新生导师  1 招生老师
     *
     * @mbggenerated
     */
    private Integer identify;

    /**
     * 备注
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * 备注扩展
     *
     * @mbggenerated
     */
    private String remarkExtend;

    /**
     * 创建时间
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * 0未删除 1 已删除
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.id
     *
     * @return the value of zhaoban_user_student.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.id
     *
     * @param id the value for zhaoban_user_student.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.admin_user_id
     *
     * @return the value of zhaoban_user_student.admin_user_id
     *
     * @mbggenerated
     */
    public String getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.admin_user_id
     *
     * @param adminUserId the value for zhaoban_user_student.admin_user_id
     *
     * @mbggenerated
     */
    public void setAdminUserId(String adminUserId) {
        this.adminUserId = adminUserId == null ? null : adminUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.stu_id
     *
     * @return the value of zhaoban_user_student.stu_id
     *
     * @mbggenerated
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.stu_id
     *
     * @param stuId the value for zhaoban_user_student.stu_id
     *
     * @mbggenerated
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.identify
     *
     * @return the value of zhaoban_user_student.identify
     *
     * @mbggenerated
     */
    public Integer getIdentify() {
        return identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.identify
     *
     * @param identify the value for zhaoban_user_student.identify
     *
     * @mbggenerated
     */
    public void setIdentify(Integer identify) {
        this.identify = identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.remark
     *
     * @return the value of zhaoban_user_student.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.remark
     *
     * @param remark the value for zhaoban_user_student.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.remark_extend
     *
     * @return the value of zhaoban_user_student.remark_extend
     *
     * @mbggenerated
     */
    public String getRemarkExtend() {
        return remarkExtend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.remark_extend
     *
     * @param remarkExtend the value for zhaoban_user_student.remark_extend
     *
     * @mbggenerated
     */
    public void setRemarkExtend(String remarkExtend) {
        this.remarkExtend = remarkExtend == null ? null : remarkExtend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.create_time
     *
     * @return the value of zhaoban_user_student.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.create_time
     *
     * @param createTime the value for zhaoban_user_student.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.update_time
     *
     * @return the value of zhaoban_user_student.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.update_time
     *
     * @param updateTime the value for zhaoban_user_student.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhaoban_user_student.is_delete
     *
     * @return the value of zhaoban_user_student.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhaoban_user_student.is_delete
     *
     * @param isDelete the value for zhaoban_user_student.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}